version: '3'

services:
  db:
    image: mongo:4.4.1
    volumes:
      - ./data:/data/db

  todo:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      DB_CONNECT_URI: mongodb://db/todo-bitpanda

volumes:
  data: